services:
  label-studio:
    image: heartexlabs/label-studio:1.13.1
    container_name: biolit-label-studio
    ports:
      - "8080:8080"
    environment:
      LABEL_STUDIO_BASE_DATA_DIR: /label-studio/data
      LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED: "true"
      LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT: /label-studio/files
      LABEL_STUDIO_HOST: http://localhost:8080
      LABEL_STUDIO_INTERNAL_HOST: http://label-studio:8080
    volumes:
      - ../data/label-studio:/label-studio/data
      - ../data/label-studio/files:/label-studio/files:ro
